[package]
name = "files_nvim"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[dependencies]
dashmap = "6"
thiserror = "2"
rayon = "1"
crossbeam-channel = "0.5"
tree_magic_mini = "3"
open = "5"
unwrap_or = "1"

nvim-oxi = { git = "https://github.com/SCJangra/nvim-oxi.git", branch = "main", features = ["neovim-nightly", "libuv"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
assertables = "9"
tempfile = "3"
